parameters:
    security.firewall.class: MediaMonks\FirewallFilterBundle\Security\Http\Firewall
    security.firewall.map.class: MediaMonks\FirewallFilterBundle\Security\FirewallMap

services:
    media_monks.firewall_filter.authentication_provider:
        abstract: true
        class: MediaMonks\FirewallFilterBundle\Security\Authentication\Provider\FirewallFilterProvider

    media_monks.firewall_filter.listener:
        class: MediaMonks\FirewallFilterBundle\Security\Listener\FirewallFilterLoginListener
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    media_monks.firewall_filter.firewall_listener:
        abstract: true
        class: MediaMonks\FirewallFilterBundle\Security\Firewall\FirewallFilterListener

    media_monks.firewall_filter.logout_handler:
        abstract: true
        class: MediaMonks\FirewallFilterBundle\Security\Http\Logout\LogoutFirewallHandler